# -*- coding: utf-8 -*-
"""Gradio Imagetotext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R3LALbNCnK00pCpojjL1D3MFkCOSUnGX

Gradio \\: USE image to Text Prompt...
"""

!pip install gradio
import gradio as gr

gr.Interface.load("models/Salesforce/blip-image-captioning-base").launch()

import sys
print(sys.version)